### PR TITLE
Yarn upgrade all packages to latest

### PR DESCRIPTION
**Pull request by zachmullen**
This changeset is just a result of running `yarn upgrade -L`. The demo app builds and runs cleanly.

### CODE REVIEW

**Comment by zachmullen** [comment]
Except for `@vue/test-utils`, which doesn't work on the latest version. That will require a separate investigation, because I have no idea why our tests are failing there.

**Comment by zachmullen** [comment]
TODO need to update our linter rules

**Comment by zachmullen** [comment]
[This line](https://github.com/airbnb/javascript/blob/6d05dd898acfec3299cc2be8b6188be542824965/packages/eslint-config-airbnb-base/rules/imports.js#L236) breaks eslint... not sure what's up there.

**Comment by zachmullen** [comment]
Relevant thread: https://github.com/airbnb/javascript/issues/2227

**Comment by subdavis** [comment]
@zachmullen might as well bump the package version in package.json ?

**Pull request merged**
