### PR TITLE
Circleci/deploy2

### PR DESCRIPTION
**Pull request by subdavis**
Duplicate of #70 because webhooks failed.

Edit: that didn't work at all as I intended

### CODE REVIEW

**Comment by zachmullen** [comment]
It seems like we need to change the expected status checks

**Comment by zachmullen** [comment]
What's the rationale for separating this into 3 separate CircleCI jobs? Since the dependency graph is just a line (no parallelism), would it make more sense to simply combine them as steps of the same job?

**Comment by subdavis** [comment]
Fixed the expected status checks.

We could definitely combine the first two jobs. 

I used branch filtering to prevent deployments on anything except the master branch -- this seems like the preferred way to accomplish that with CircleCI.

Ideally we would also use CircleCI to deploy the UMD library, which could run parallel to a GH Pages deployment.

**Comment by subdavis** [comment]
Alright, combined the first 2.

**Pull request merged**
