### PR TITLE
Add option to use Girder-Authorization for auth.

### PR DESCRIPTION
**Pull request by subdavis**
I don't like adding this back, but I can't function without it.  As long as girder supports this auth mechanism, I feel like having the option to use it is within scope here.

### CODE REVIEW

**Comment by subdavis** [comment]
@zachmullen ptal when you have a chance.

**Comment by zachmullen** [comment]
> but I can't function without it

Why is that? In what context do you need to use one over the other?

**Comment by subdavis** [comment]
I think I mentioned it a while back, but I'm working behind a proxy that filters out all `Authorization` headers.  Under normal circumstances I would say such a patch has no business being in this library, but girder luckily supports it.

**Comment by zachmullen** [comment]
Hopefully we aren't subverting some security policy by passing basic auth via a different header...

**Comment by subdavis** [comment]
As far as I can tell, the proxy is just configured improperly.  It should pass Authorization along when a request comes in that is already authorized with the proxy through another means, such as with a cookie.

**Pull request merged**
