### PR TITLE
v2.3.1

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Review by zachmullen — APPROVED** [review]

**Comment by zachmullen** [comment]
Tag has been pushed. 2.3.1 should be published in a few minutes.

**Comment by scottwittenburg** [comment]
> Tag has been pushed. 2.3.1 should be published in a few minutes.

Thanks for the lightning fast action @zachmullen 😁

**Comment by subdavis** [comment]
@scottwittenburg @zachmullen 2.3 was an unintended release, and I was planning to scrub it from NPM pending a discussion.

The changes introduced in #293 are significant enough to require a major version update, so I was going to suggest moving to 3.0.0 after https://github.com/girder/girder_web_components/pull/297 gets resolved, which I haven't had time to fix.

Do you need the changes introduced in 2.3.0 (ts, import restructure)?

We can certainly keep going with 2.3, but it would somewhat contradict semver guidelines.

**Comment by subdavis** [comment]
I see, the point was to release the changes from #299.

@scottwittenburg you should know that upgrading your project to 2.3 will break your project.

This library hasn't had so much traffic that it has been necessary to maintain a "stable" branch and a "next" branch to allow us to push minor patches like #299 while working on larger changes.

Apologies for the confusion.  Let me know what you want do now.

**Comment by zachmullen** [comment]
I don't have a strong preference.

**Comment by scottwittenburg** [comment]
@subdavis We're currently on `2.2.6` and we're only using only the user login/registration dialog in our application, I don't think we necessarily need anything from `2.3`, other than the newer `axios`.  And based on your last comment, it sounds like getting that change will require some other work.

Other than that, I don't have any preference which path you take.  But when you decide what you're going to do, I'll get in touch about the path forward for my application.  Thanks!

**Comment by subdavis** [comment]
Unless someone has a better suggestion, I'm going to

* Get #297 merged
* Release 3.0.0
* Scrub 2.3.0, 2.3.1
* Write a short migration guide (should be easy, just have to change import paths)

**Comment by scottwittenburg** [comment]
> * Write a short migration guide (should be easy, just have to change import paths)

That would be great, thanks!

**Pull request merged**
