### PR TITLE
fix for building girder web components from external app

### PR DESCRIPTION
**Pull request by subdavis**
Other apps can't resolve '@'

### CODE REVIEW

**Comment by zachmullen** [comment]
Good catch, is there a way we can catch this with our linter?

**Comment by subdavis** [comment]
Maybe this?

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md#importno-unresolved

**Comment by zachmullen** [comment]
Thanks for the link, we can merge this and I'll look into a linter solution.

**Comment by subdavis** [comment]
I installed that plugin and tried a few things, but they all allowed the @ import.

**Pull request merged**
